# Generated by Django 4.2 on 2024-04-10 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_sessionseat_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_seats', to='cinema.seat'),
        ),
    ]
