# Generated by Django 4.2 on 2024-04-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_activity',
        ),
    ]
