# Generated by Django 4.2 on 2024-04-18 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_request',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 19, 2, 4, 34, 55015)),
            preserve_default=False,
        ),
    ]
